# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-28 08:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rest_api', '0006_auto_20170327_0527'),
    ]

    operations = [
        migrations.AddField(
            model_name='eduadmin',
            name='username',
            field=models.CharField(default='', max_length=150),
            preserve_default=False,
        ),
    ]
