# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-28 14:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rest_api', '0008_auto_20170328_1256'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='class_in',
            field=models.CharField(max_length=128, null=None),
        ),
        migrations.AlterField(
            model_name='student',
            name='grade',
            field=models.CharField(max_length=32, null=None),
        ),
    ]
