# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-29 10:56
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rest_api', '0009_auto_20170328_1408'),
    ]

    operations = [
        migrations.CreateModel(
            name='CourseGroupRelation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creator', models.CharField(max_length=150, null=True)),
                ('create_time', models.DateTimeField(auto_now_add=True)),
                ('updater', models.CharField(max_length=150, null=True)),
                ('update_time', models.DateTimeField(auto_now=True)),
                ('available', models.BooleanField(default=True)),
                ('deleted', models.BooleanField(default=False)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='CourseMeta',
            fields=[
                ('creator', models.CharField(max_length=150, null=True)),
                ('create_time', models.DateTimeField(auto_now_add=True)),
                ('updater', models.CharField(max_length=150, null=True)),
                ('update_time', models.DateTimeField(auto_now=True)),
                ('available', models.BooleanField(default=True)),
                ('deleted', models.BooleanField(default=False)),
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('caption', models.CharField(max_length=150)),
                ('number_courses', models.IntegerField(default=0)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='CourseUnit',
            fields=[
                ('creator', models.CharField(max_length=150, null=True)),
                ('create_time', models.DateTimeField(auto_now_add=True)),
                ('updater', models.CharField(max_length=150, null=True)),
                ('update_time', models.DateTimeField(auto_now=True)),
                ('available', models.BooleanField(default=True)),
                ('deleted', models.BooleanField(default=False)),
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='organization',
            name='number_course_groups',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='organization',
            name='number_course_meta',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='organization',
            name='number_course_units',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='organization',
            name='number_courses',
            field=models.IntegerField(default=0),
        ),
        migrations.CreateModel(
            name='Course',
            fields=[
                ('courseunit_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='rest_api.CourseUnit')),
                ('caption', models.CharField(max_length=150)),
                ('start_time', models.DateField()),
                ('end_time', models.DateField()),
            ],
            options={
                'abstract': False,
            },
            bases=('rest_api.courseunit',),
        ),
        migrations.CreateModel(
            name='CourseGroup',
            fields=[
                ('courseunit_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='rest_api.CourseUnit')),
                ('caption', models.CharField(max_length=150, null=True)),
                ('number_courses', models.IntegerField(default=0)),
            ],
            options={
                'abstract': False,
            },
            bases=('rest_api.courseunit',),
        ),
        migrations.AddField(
            model_name='courseunit',
            name='organization',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='course_units', to='rest_api.Organization'),
        ),
        migrations.AddField(
            model_name='coursemeta',
            name='organization',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='course_meta', to='rest_api.Organization'),
        ),
        migrations.AddField(
            model_name='coursegrouprelation',
            name='organization',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='course_group_relations', to='rest_api.Organization'),
        ),
        migrations.AddField(
            model_name='coursegrouprelation',
            name='course',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='group_relations', to='rest_api.Course', to_field='id'),
        ),
        migrations.AddField(
            model_name='coursegrouprelation',
            name='group',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='course_relations', to='rest_api.CourseGroup', to_field='id'),
        ),
        migrations.AddField(
            model_name='coursegroup',
            name='courses',
            field=models.ManyToManyField(related_name='groups', through='rest_api.CourseGroupRelation', to='rest_api.Course'),
        ),
        migrations.AddField(
            model_name='course',
            name='meta',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='courses', to='rest_api.CourseMeta'),
        ),
    ]
