# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-30 01:55
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rest_api', '0010_auto_20170329_1056'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='coursegrouprelation',
            name='course',
        ),
        migrations.RemoveField(
            model_name='coursegrouprelation',
            name='group',
        ),
        migrations.RemoveField(
            model_name='coursegrouprelation',
            name='organization',
        ),
        migrations.RemoveField(
            model_name='coursegroup',
            name='courses',
        ),
        migrations.DeleteModel(
            name='CourseGroupRelation',
        ),
    ]
