# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-30 01:55
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rest_api', '0011_auto_20170330_0155'),
    ]

    operations = [
        migrations.CreateModel(
            name='CourseGroupRelation',
            fields=[
                ('creator', models.CharField(max_length=150, null=True)),
                ('create_time', models.DateTimeField(auto_now_add=True)),
                ('updater', models.CharField(max_length=150, null=True)),
                ('update_time', models.DateTimeField(auto_now=True)),
                ('available', models.BooleanField(default=True)),
                ('deleted', models.BooleanField(default=False)),
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='group_relations', to='rest_api.Course', to_field='id')),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='course_relations', to='rest_api.CourseGroup', to_field='id')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='course_group_relations', to='rest_api.Organization')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='coursegroup',
            name='courses',
            field=models.ManyToManyField(related_name='groups', through='rest_api.CourseGroupRelation', to='rest_api.Course'),
        ),
    ]
